#!/bin/sh php
<?php

declare(strict_types=1);

use Dotenv\Dotenv;
use League\Container\Container;
use Symfony\Component\Console\Application;

define("ROOT_DIR", dirname(__DIR__));
if (!defined('CONSOLE_APP')) {
    define('CONSOLE_APP', true);
}
require 'vendor/autoload.php';

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();
/**
 * @var Container $container
 */
require 'app/dependencies.php';
$consoleApp = new Application('App Console');
$consoleApp->addCommands(array_map(fn($command) => $container->get($command), require 'app/Commands/Commands.php'));
$consoleApp->run();
